services:
  app:
    #banco de dados precisa iniciar para o app rodar
    image: lucas10sh/psoriasis-model
    build: "./"
    ports:
      - "8080:8080"
    container_name: cnn_container
    restart: on-failure

    volumes:
      - ./model_logs:/runs
    command: python -m application.networks.pipeline -e 4 -f 1


volumes:
  app:
    driver: local