apiVersion: v1
kind: Service
metadata:
  name: psoriasis-model-service
spec:
  type: NodePort  # Expõe o serviço na rede do cluster
  selector:
    app: psoriasis-model  # Seleciona o Pod com o rótulo 
  ports:
    - protocol: TCP
      port: 8000       # Porta interna do serviço
      targetPort: 8000 # Porta do container que será mapeada
      nodePort: 30007  # Porta no nó onde o serviço ficará acessível (ajuste conforme necessário)
